### PR TITLE
Update 91-pulseaudio-sennheiser-gsp670.rules

### PR DESCRIPTION
**Pull request by vk496**
Last dongle firmware update

### CODE REVIEW

**Comment by szszoke** [comment]
Hey!

The order if the USB interfaces have changed and additional changes had to be made to the PulseAudio profiles as well.
You can see that work in this branch: https://github.com/szszoke/sennheiser-gsp670-pulseaudio-profile/tree/new-dongle-firmware

There is a new patch that adds a quirk to the USB audio driver for this device. Did you test your change with it?

**Comment by vk496** [comment]
Just testing right now. The new firmware seems to break stuff with the config from master. I will try to test the other branch (didn't saw it :smile: ) and report here

**Comment by szszoke** [comment]
The other branch does include your change and some more.

**Comment by vk496** [comment]
Doesn't work, I will explain more in the issues

**Pull request closed without merging**
