### PR TITLE
Profile names and icons

### PR DESCRIPTION
**Pull request by hmlendea**
- Set the profile names to something nice and human-readable
 - Set the profile icons to headset icons

### CODE REVIEW

**Comment by szszoke** [comment]
Hello!

Thank you for your contribution!

The contents of this repository should be merged to the main PulseAudio project at some point. In order to do that, I need your consent to take your work and submit it to the main PulseAudio project. This would also involve relicensing your work to whatever license is used by the relevant PulseAudio project at the time of submission.

**Comment by hmlendea** [comment]
Hello.

I would be more than happy for this change to be merged into main PulseAudio.
I thereby give my consent to merge it there, and to relicense it.

**Comment by szszoke** [comment]
Great!

I will likely get some time to test and hopefully merge this PR by the end of next week.

**Comment by szszoke** [comment]
In the meantime, please reword your commit messages so that they fit in with the style used in the repository.

In your case the most fitting prefix yould be `feat:` followed by the changes you made in all lowercase. Please do not use past tense (i.e. write `add` instead of ~`added`~).

**Comment by hmlendea** [comment]
Done

**Review by szszoke — APPROVED** [review]

**Comment by szszoke** [comment]
Merged. I will create a new release as soon as #1 is addressed.

**Pull request merged**
